#!/bin/bash

func()
{
if [ $1 -gt $2 ]
then
    min=$2
    max=$1
else
    min=$1
    max=$2
fi

if [ $min -lt 0 ]
then
    echo "$min is less than 0, quit"
    exit 1
fi

for ((i=$min;i<=$max;i++))
do
  flag=0
  if [ $i -lt 2 ]
  then
	continue
  fi
  for ((j=2;j<$i;j++))
  do
     if [ $(($i % $j)) -eq 0 ]
     then
	flag=1
	break
     fi
  done
  if [ $flag -eq 0 ]
  then
      echo $1
  fi
done
}

check()
{
if [ $# -ne 2 ]
then
    echo "The quantity of the parameters is $#, quit."
    exit 1
fi

if ![[ "$1" =~ "^[0-9]+$" ]]
then
    echo "$1 is not a positive integer, quit."
    exit 2
fi


if ![[ "$2" =~ "^[0-9]+$" ]]
then
    echo "$2 is not a positive integer, quit."
    exit 2
fi
}

check $0
func $0
